export const ActionTypes=
{
    CHECK_LOGGED:'CHECK_LOGGED',
    ADMIN_LOGIN:'ADMIN_LOGIN',
    ADMIN_LOGIN_FAIL:'ADMIN_LOGIN_FAIL',
    ADMIN_LOGOUT:'ADMIN_LOGOUT',
    ADMIN_LOGOUT_FAIL:'ADMIN_LOGOUT_FAIL',
    
    GET_USER_DATA:'GET_USER_DATA',
    
    REGISTER:'REGISTER',
    REGISTER_FAIL:'REGISTER_FAIL',
    

}