export const ActionTypes=
{
    CHECK_LOGGED:'CHECK_LOGGED',
    LOGIN:'LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGOUT:'LOGOUT',
    LOGOUT_FAIL:'LOGOUT_FAIL',
    
    GET_USER_DATA:'GET_USER_DATA',
    
    REGISTER_ATTEMPT:'REGISTER_ATTEMPT',
    REGISTER_FAIL:'REGISTER_FAIL',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',


    SET_PROFILE:'FETCH_PROFILE',
    PROFILE_UPDATE_ATTEMPT:'PROFILE_UPDATE_ATTEMPT',
    PROFILE_UPDATE_FAIL:'PROFILE_UPDATE_FAIL',
    PROFILE_UPDATE_SUCCESS:'PROFILE_UPDATE_SUCCESS',




    UPLOAD_STORY_ATTEMPT:'UPLOAD_STORY_ATTEMPT',
    UPLOAD_STORY_SUCCESS:'UPLOAD_STORY_SUCCESS',
    UPLOAD_STORY_FAIL:'UPLOAD_STORY_FAIL',

    

}